server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:8082
  data:
    rest:
      basePath: /v1
      defaultPageSize: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/my-books
    username: my-books
    password: secret
  #  jpa:
  #    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jackson:
    serialization:
      fail-on-empty-beans: false

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14