server:
  port: 8081

spring:
  data:
    rest:
      basePath: /v1
      defaultPageSize: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/my-books2
    username: my-books
    password: secret
  #  jpa:
  #    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jackson:
    serialization:
      fail-on-empty-beans: false

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14



