package higor.mybooks.entity;

public enum CategoryType {
  SOFTWARE_DEVELOPMENT,
  SCIENCE,
  SCIFI,
  CONSPIRATION_THRILLER,
  ROMANCE,
  TALE,
  FANTASY,
  HORROR,
  CLASSIC,
  ACTION_AND_ADVENTURE,
  NOVEL,
  DETECTIVE_AND_MISTERY,
  HISTORICAL_FICTION,
  LITERATY_FICTION,
  COMIC_BOOK_OR_GRAPHIC_NOVEL,
  SHORT_STORIES,
  SUSPENSE_AND_THRILLERS,
  BIOGRAPHIES_AND_AUTOBIOGRAPHIES,
  COOKBOOKS,
  ESSAYS,
  HISTORY,
  MOMOIR,
  POETRY,
  SELF_HELP,
  TRUE_CRIME
}
